name: Hello, World!

on: push

jobs:
  show-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Show github properties
        run: | 
          echo ${{ github.workflow }}
          echo ${{ github.ref }}
          echo ${{ github.sha }}
